SELECT DEP_ID,COUNT(DEP_ID) AS "NUMBER OF EMPLOYEES", AVG(SALARY) AS "AVERAGE SALARIES"
FROM EMPLOYEES
GROUP BY DEP_ID
HAVING COUNT(DEP_ID) < 4
ORDER BY AVG(SALARY);

SELECT F_NAME, L_NAME FROM EMPLOYEES
WHERE F_NAME LIKE 'S%';

SELECT * FROM EMPLOYEES
ORDER BY B_DATE;

SELECT DEP_ID,AVG(SALARY) AS "AVG_SALARY"
FROM EMPLOYEES
GROUP BY DEP_ID
HAVING AVG_SALARY >= 60000;

SELECT DEP_ID,AVG(SALARY) AS "AVG_SALARY"
FROM EMPLOYEES
GROUP BY DEP_ID
HAVING AVG_SALARY >= 60000
ORDER BY AVG_SALARY DESC;